blank_issues_enabled: false
contact_links:
  - name: GitHub Communiti Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer here
  - name: GitHub Security Bounty
    url: https://bounty.github.com/
    about: Please report secutiry vulnerabilities here.
